image: 
  repository: julian210/complete-devops-project
  tag: 57f2b69
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
